updating tos errors
mobilecoinofficial/full-service pull request #184
Opened 2021-08-17 22:14 UTC by BrianCorbin

2021-08-17 22:22 UTC, jcape requested changes
All the HTTP links should be https, and there are inconsistencies elsewhere in this text about what is used where.

2021-08-17 22:22 UTC, jcape commented on TERMS-OF-USE.md
> +Please read these Terms carefully before you start to use any MobileCoins and any MobileCoin Wallet. By acquiring or otherwise obtaining MobileCoins, using or transferring MobileCoins or obtaining, a
The `[www.buymobilecoin.us]` text should be `[www.buymobilecoin.us](https://www.buymobilecoin.com/)`

2021-08-18 01:57 UTC, joekottke approved these changes

2021-08-18 02:04 UTC, sugargoat approved these changes

2021-08-18 02:39 UTC, the-real-adammork commented on TERMS-OF-USE.md
> +# **TERMS OF USE** **FOR MOBILECOINS AND MOBILECOIN WALLETS**
```suggestion
# **TERMS OF USE**  **FOR MOBILECOINS AND MOBILECOIN WALLETS**
```

2021-08-18 02:41 UTC, the-real-adammork commented on TERMS-OF-USE.md
> +# **TERMS OF USE** **FOR MOBILECOINS AND MOBILECOIN WALLETS**
this change will make the file equal to the other ones which have 'md5' hash:

`TERMS-OF-USE.md) = 6fc7a4a7a21915add9f36fd20da4e8d3`

2021-08-18 04:37 UTC, merged