Gift codes
mobilecoinofficial/full-service pull request #21
Opened 2021-01-08 23:15 UTC by sugargoat

### Motivation

Gift codes are miniature accounts that contain a single Txo, for use as delivering gifts of MOB.

### In this PR
* Adds the Gift Code data model
* Adds the Gift Code Service, including create, consume, and check_status.

[WS-50](https://mobilecoin.atlassian.net/browse/WS-50)

2021-01-09 00:36 UTC, eranrund requested changes
I think the gift code stuff looks mostly reasonable but to be honest it is a lot of code so I can't guarantee I didn't miss anything or that this solves whatever it is this is set to solve. The issues I have with this PR are:
1) the JSON String/u64 spills into places it shouldn't.
2) This includes all the encryption stuff/password hash stuff that I wasn't happy about, making it both harder to review, and contain code that I think is not optimal
3) Too liberal use of unwraps/expects
I'm trusting you that the happy flow actually works as expected (both in cases a person gifts themselves for whatever reason, and when two unrelated instances of the service gift each-other), I haven't tested it.

2021-01-09 00:36 UTC, eranrund commented on API.md
> +  "value": "2000000000000",
Having the value feels questionable to me since there's no guarantee it actually matches the TxOut.

2021-01-09 00:36 UTC, eranrund commented on README.md
> +#### Change Password
I don't think this is available in this branch...

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +        fee: Option<String>,
Pretty weird that this is a `String` in Rust world.

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +    ///  3. Wait for the transaction to land
It doesn't look like the implementation of `build_and_submit_gift_code` is waiting for anything, it just submits the transaction.

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +        poll_interval: Option<u64>,
Its implicit that these are seconds. This should be a `Duration`

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +                            .expect("Could not get password hash"),
I don't think expect is appropriate.

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +        Ok(())
What is this for?

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +                .unwrap();
Unwrap is not reasonable here imo.

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +                .unwrap();
This applies to all the other unwraps that are sprinkled in this method.

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +        std::thread::sleep(std::time::Duration::from_secs(5));
I don't think this is reasonable, what happens if it takes more than 5 seconds?

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +        log::info!(self.logger, "\x1b[1;33m GOT TXOS = {:?}\x1b[0m", txos);
We don't do colors in the log messages

2021-01-09 00:36 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +                log::info!(self.logger, "Registering gift code");
This should have more information like the b58 or the id or anything that makes it easier to debug, this applies to other log messages in this method.

2021-01-09 00:37 UTC, eranrund commented on full-service/src/service/gift_code.rs
> +    fn register_gift_code(
This name is confusing to me

2021-02-23 23:51 UTC, sugargoat commented
Closing for now - will re-open when this is ready for review.

2021-02-23 23:51 UTC, closed without merging