Feature/merge view only and normal db models
mobilecoinofficial/full-service pull request #374
Opened 2022-06-13 20:37 UTC by BrianCorbin

2022-06-17 20:28 UTC, Shramp requested changes
Diff is a bit large for deep understanding of everything happening here, but most of it makes sense to me and looks like. Just a few minor questions/requests

2022-06-17 20:28 UTC, Shramp commented on full-service/src/service/account.rs
> +    AccountIsViewOnly(AccountID),
I think these two errors still need to be implimented?

2022-06-17 20:28 UTC, Shramp commented on full-service/src/util/encoding_helpers.rs
> +pub fn ristretto_public_to_vec(key: &RistrettoPublic) -> Vec<u8> {
stoked to see that these helpers are being used!

2022-06-24 18:30 UTC, christian-oudard approved these changes

2022-06-26 20:06 UTC, christian-oudard commented on full-service/migrations/2022-06-13-204000_api_v3/up.sql
>    id INTEGER NOT NULL PRIMARY KEY,
This is starting the new 2.0 release series, and it seems prohibitively difficult at this time to do the data migrations necessary to untangle the separate view-only accounts. So, we decided to wipe the current migration table, and start afresh, requiring people to re-import.

2022-06-27 16:00 UTC, Shramp approved these changes
LGTM once merge conflicts are resolved

2022-06-27 16:40 UTC, merged