Move API documentation to API.md
mobilecoinofficial/full-service pull request #42
Opened 2021-02-20 22:08 UTC by sugargoat

### Motivation

The current API documentation is spread across two files (the README and API.md). This PR moves the usage from the README to API.md.

### In this PR
* Moves usage documentation from README to API.md
* Fixes typos and wording
* Adds usage for the get-raw-object methods

2021-02-22 21:33 UTC, christian-oudard commented
Looks good! The only change that I notice is needed is to update the `API.md` link on line 86 of README.md to link to `API_v1.md`

2021-02-22 21:34 UTC, christian-oudard requested changes
Looks good! The only change that I notice is needed is to update the `API.md` link on line 86 of README.md to link to `API_v1.md`

2021-02-22 21:57 UTC, jcape approved these changes
Approved pending API.md link fix.

2021-02-22 22:34 UTC, christian-oudard approved these changes
Copying jcape, approved pending API_v1.md link.

2021-02-23 00:42 UTC, jcape commented on README.md
> +For usage and API specification, see [API.md](./API.md).
```suggestion
For usage and API specification, see [API_v1.md](./API_v1.md).
```

2021-02-23 01:24 UTC, merged