check for xcode 12
mobilecoinofficial/full-service pull request #634
Opened 2022-12-13 01:49 UTC by cxloe

### Motivation

If FS is built with Xcode 13 or newer , this leads to lots of `BadSignature` errors which can be frustrating. Now the build script checks if the version is 12, and prompts to switch if not.

2022-12-15 15:28 UTC, brucek requested changes

2022-12-15 15:28 UTC, brucek commented on tools/.shared-functions.sh
> +      echo
According to the description of the issue, I think anything other than XCode 12 should fail here, right?
1. maybe `minimum_xcode_version` should be something more like `supported_xcode_version`?
2. This test as written passes with XCode 13 & 14, which it should not, correct?

2022-12-15 17:57 UTC, eranrund commented
@the-real-adammork are your changes to mbedtls supposed to remedy the issue with the newer xcode versions?

2022-12-15 17:58 UTC, eranrund commented on tools/.shared-functions.sh
> +    if [[ $(printf '%s\n' "$xcode_version" "$minimum_xcode_version" | sort -V | head -n1) == "$xcode_version" ]]; then
Nit: If the `if` clause is empty and the `else` code has the logic, it means the condition the `if` is testing for needs to be reversed

2022-12-15 19:11 UTC, the-real-adammork commented
> @the-real-adammork are your changes to mbedtls supposed to remedy the issue with the newer xcode versions?

yes it fixes the issue with xcode 13/14. I got stuck trying to fix the mac-catalyst target for libmobilecoin, but fs doesnt need that so Ill make a mobilecoin PR with what I have.

2022-12-15 19:29 UTC, the-real-adammork commented
> > @the-real-adammork are your changes to mbedtls supposed to remedy the issue with the newer xcode versions?
> 
> yes it fixes the issue with xcode 13/14. I got stuck trying to fix the mac-catalyst target for libmobilecoin, but fs doesnt need that so Ill make a mobilecoin PR with what I have.

PR - https://github.com/mobilecoinfoundation/mobilecoin/pull/2962

2023-01-06 07:37 UTC, briancorbin commented
Not necessary as issue is resolved with PR - https://github.com/mobilecoinfoundation/mobilecoin/pull/2962

2023-01-06 07:37 UTC, closed without merging