Asynchronous Python client and CLI for Full-Service API v2
mobilecoinofficial/full-service pull request #695
Opened 2023-02-06 18:25 UTC by christian-oudard

* Python client class for full-service API v2, supporting both synchronous and
  asynchronous operation
* Command line interface to conveniently use full-service
* Integration tests to validate correct functionality of both the API and the
  Python client.

2023-02-09 21:33 UTC, briancorbin reviewed
This looks good on first pass, let me get this running on my machine and will approve once it's looking good :) Thank you!

2023-02-09 23:16 UTC, briancorbin requested changes
Remove unused old code and any dead code / commented code

2023-02-09 23:38 UTC, christian-oudard commented on python/mobilecoin/token.py
> +        assert isinstance(other, Amount)
The tracebacks end up looking like this, which I find to be pretty clear.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/christian/third-party-code/full-service/python/mobilecoin/token.py", line 104, in __add__
    assert isinstance(other, Amount)
AssertionError
```

2023-02-09 23:38 UTC, christian-oudard commented on python/tests/test_client_async.py
> +# import asyncio
This file has been removed, it was draft code.

2023-02-09 23:39 UTC, christian-oudard commented on python/README.md
> +$ mob status
I need to add the executable to the Poetry config, but then it will be on the PATH.

2023-02-09 23:54 UTC, christian-oudard commented on python/README.md
> +$ mob status
Ok done.

2023-02-10 00:09 UTC, briancorbin approved these changes

2023-02-10 22:56 UTC, merged