Feat/reintroduce secreted status
mobilecoinofficial/full-service pull request #698
Opened 2023-02-06 22:13 UTC by pouneh

## Motivation

Currently the API responses include a "secreted" when listing balances. However, this field was unhelpfully always set to zero. Between removing the API, and reintroducing the status, we reintroduce the status.

## In this PR

We introduce 2 new txo status.

    "Created" - for output TXOs that are proposed as part of a built transaction (either not submitted, or failed)
    "Secreted" - for output TXOS that are build as part of successfully submitted transactions that go to a wallet that does NOT belong to the sender

2023-02-07 19:15 UTC, briancorbin requested changes
This looks good so far, but it could use a bunch more tests, both directly in the db/txo.rs file and in the e2e tests. I would recommend creating tests for a variety of possible situations that the database could be in to ensure we get the correct status at the correct times.

It would also be a good idea to test that querying an individual txo results in the correct status, again both in the e2e tests as well as the db/txo.rs tests

2023-02-07 19:15 UTC, briancorbin commented on full-service/src/json_rpc/v1/models/txo.rs
> +            db::txo::TxoStatus::Created | db::txo::TxoStatus::Secreted => todo!(),
How come this is left as todo?

2023-02-07 19:15 UTC, briancorbin commented on tools/build-fs.sh
> +            CONSENSUS_ENCLAVE_CSS=`pwd`/mobilecoin/target/docker/release/consensus-enclave.css
Can we move these changes to a separate PR? Out of scope for this review

2023-02-07 19:15 UTC, briancorbin commented on tools/run-fs.sh
> +            MC_TX_SOURCE_URL="file:///home/$USER/full-service/mobilecoin/target/docker/release/mc-local-network/node-ledger-distribution-0,file:///home/$USER/full-service/mobilecoin/target/docker/rel
Can we move these changes to a separate PR? Out of scope for this review

2023-02-07 19:15 UTC, briancorbin commented on tools/test.sh
> +
Can we move these changes to a separate PR? Out of scope for this review

2023-02-13 23:03 UTC, christian-oudard approved these changes

2023-02-13 23:29 UTC, briancorbin approved these changes
This looks good, thanks for all of the changes!

2023-02-14 00:36 UTC, merged