Update txos fully when syncing
mobilecoinofficial/full-service pull request #714
Opened 2023-02-15 23:51 UTC by pouneh

### Motivation

When a txo is synced from the database but already exists, it should update all of the information, not just the new expected info, in the case that the information from the TxProposal was malformed or incorrect in any way.

### In this PR
We additionally update
1. Amount (value, token_id)
2. target_key
3. public_key
4. e_fog_hint

2023-02-16 03:21 UTC, briancorbin requested changes
This is good, but I would like to understand why we're not encoding it the second time around with mc util serial like we are the first time

2023-02-16 03:21 UTC, briancorbin commented on full-service/src/db/txo.rs
> +                    &txo.public_key,
So, these 2 should definitely be encoded as things currently work, and it's a bit concerning that they're passing tests without...

2023-02-16 03:21 UTC, briancorbin commented on full-service/src/db/txo.rs
> +        e_fog_hint: &Vec<u8>,
Perhaps we leave these not updated for now until we understand better why they are passing tests without being protobuf encoded.

2023-02-16 03:27 UTC, briancorbin requested changes

2023-02-16 03:27 UTC, briancorbin commented on full-service/src/db/txo.rs
> +                    &txo.public_key,
Oh I see what's going on...

2023-02-16 03:27 UTC, briancorbin commented on full-service/src/db/txo.rs
>              Ok(txo) => {
This line is overwriting the `TxOut` that is passed in under the variable name `txo`, which is why the encoding is weird. I would recommend changing the name of either one of them as to preserve both of their information sets

2023-02-16 21:09 UTC, christian-oudard approved these changes

2023-02-17 01:26 UTC, briancorbin approved these changes
Thanks for the changes, this looks good now :)

2023-02-17 19:18 UTC, merged