include FAQ in SUMMARY.md
mobilecoinofficial/full-service pull request #740
Opened 2023-03-02 19:41 UTC by trunkafunk

include link to FAQ in gitbook

### Motivation
include and fillout the FAQ section for FS

2023-03-08 23:57 UTC, brucek requested changes
Some minor nits but this looks generally good otherwise

2023-03-08 23:57 UTC, brucek commented on docs/FAQ.md
> +By using the **first_block_index** param, a user can specify the starting block for that entropy if it is known. Newly created accounts are given a starting block index.
Maybe add something like:

Any transactions that occurred before the **first_block_index** will not be tracked, potentially leading to invalid balances or denied transactions.

2023-03-08 23:57 UTC, brucek commented on docs/FAQ.md
> +Using the [`get_network_status`](https://mobilecoin.gitbook.io/full-service-api/api-endpoints/v2/network-status/get_network_status) API is the cleanest way to determine if FullService is successfully
Full Service is 2 words.  Should probably always write it out completely in public docs like these.

2023-03-08 23:57 UTC, brucek commented on docs/FAQ.md
> +## How can I tell if FS is able to properly communicate with the Mobilecoin blockchain?
FS --> Full Service

2023-03-08 23:57 UTC, brucek commented on docs/FAQ.md
> +For instance, if your version of FS can't decipher blocks after a mobilecoin-core update, you may see something like this:
FS --> Full Service

2023-03-08 23:57 UTC, brucek commented on docs/SUMMARY.md
> +* [What is the Precision of Mob?](FAQ.md#what-is-the-precision-of-mob)
I feel like MOB should be capitalized?

2023-03-09 02:17 UTC, trunkafunk reviewed
Comments addressed

2023-03-09 15:48 UTC, briancorbin approved these changes

2023-03-09 19:19 UTC, brucek approved these changes

2023-03-10 15:37 UTC, merged